# Generated by Django 5.2.8 on 2025-11-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_total_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livingbudgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
    ]
