# Generated by Django 5.2.8 on 2025-11-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_alter_livingbudgetitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livingbudgetitem',
            name='type',
            field=models.CharField(choices=[('FOOD', '식비'), ('HOUSING', '주거비'), ('TRANSPORT', '교통비'), ('SHOPPING', '쇼핑비'), ('TRAVEL', '여행비'), ('STUDY_MATERIALS', '교재비'), ('ETC', '기타')], max_length=20),
        ),
    ]
