# Generated by Django 5.2.8 on 2025-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_livingbudgetitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livingbudgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
